GET https://localhost:5101/catalog/categories/?$select=CategoryId,CategoryName
###
GET https://localhost:5101/catalog/products/?$filter=startswith(ProductName, 'Ch') or (UnitPrice gt 50)
###
GET https://localhost:5101/catalog/products/?$orderby=UnitPrice desc, ProductName&$select=ProductId,ProductName,UnitPrice
###
GET https://localhost:5101/catalog/products/?$filter=startswith(ProductName, 'Cha')&$select=ProductId,ProductName,UnitPrice
###
GET https://localhost:5101/catalog/products(77)/?$select=ProductId,ProductName,UnitPrice
###
GET https://localhost:5101/catalog/products/?$orderby=ProductId desc
###
GET https://localhost:5101/catalog/categories/?$select=CategoryId,CategoryName&$expand=Products
###
GET https://localhost:5101/catalog/categories(8)/?$select=CategoryId,CategoryName&$expand=Products
###
GET https://localhost:5101/catalog/v1/products(50)/
###
GET https://localhost:5101/catalog/products
    ?$filter=contains(ProductName, 'ch') and UnitPrice lt 44.95
    &$orderby=Supplier/Country,UnitPrice
    &$select=ProductName,UnitPrice
    &$expand=Supplier
###
GET https://localhost:5101/orderSystem/customers/
    ?$expand=Orders/&$count
    &$filter=Country eq 'Germany' and Orders/$count gt 1
    &$select=CustomerId,CompanyName,Orders
