version: '3.8'

services:
  sql1:
    build: .
    image: northwind-sqlserver
    container_name: sql1
    hostname: sql1
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "dima12345++"
    volumes:
      - sql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql-data:
